### ISSUE TITLE
COP curve is not set to CentralAirSourceHeatPump 

### ISSUE THREAD

**Issue by MingboPeng** [NREL/openstudio-standards#1111]
Hi @mdahlhausen,

I am trying to understand how you set up the air source heat pump with this script. If I am understanding it correct, the COP curve is not set to the heat pump object, here you just added it to model, which means the MeteredOutputVariable for getting electricity won't work.

Is it right? Or am I missing something here. 

https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/prototypes/common/objects/Prototype.CentralAirSourceHeatPump.rb#L111-L122
![image](https://user-images.githubusercontent.com/9031066/122714083-c0d13300-d234-11eb-8089-e441657f9418.png)

**Comment by mdahlhausen** [comment]
@MingboPeng this model is an EMS code implementation of a central air source heat pump, as that object doesn't fully exist in openstudio yet.  To get the electricity, you'll need to use the output [variable listed here](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/prototypes/common/objects/Prototype.CentralAirSourceHeatPump.rb#L192-L202).

**Comment by MingboPeng** [comment]
Thanks @mdahlhausen, so I was checking the one of [model ](https://discourse.ladybug.tools/t/ironbug-air-source-heat-pump/14829/7?u=mingbopeng)that a user generated by honeybee which is using the template from openstudio standards.  But in the osm file, the [cop curve object](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/prototypes/common/objects/Prototype.CentralAirSourceHeatPump.rb#L122) is referenced in [EMSCurveOrTableIndexVariable](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/prototypes/common/objects/Prototype.CentralAirSourceHeatPump.rb#L125), which is used in [EMSMeteredOutputVariable](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/prototypes/common/objects/Prototype.CentralAirSourceHeatPump.rb#L192-L202) for getting output. It all makes sense so far.

**But my question is how does these output variable work if the source COP curve object is not assigned to any real HVAC object in the model?** 

[in.osm.txt](https://github.com/NREL/openstudio-standards/files/6691220/in.osm.txt)
Here is the user's model, the only place that references this COP curve's handle is `EnergyManagementSystem:CurveOrTableIndexVariable`, and no other HVAC object is using this curve.
![image](https://user-images.githubusercontent.com/9031066/122867633-cba0cc00-d2f7-11eb-9a16-6da4adce84cf.png)

**Comment by bonnema** [comment]
@MingboPeng, the curve is used by the [EMS program](https://github.com/NREL/openstudio-standards/blob/b123fa6fc8e0e9b6307e63f4b1d0a0f65ff83f62/lib/openstudio-standards/prototypes/common/objects/Prototype.CentralAirSourceHeatPump.rb#L177-L180) instead of directly by a "real" HVAC object in the model. This [line](https://github.com/NREL/openstudio-standards/blob/b123fa6fc8e0e9b6307e63f4b1d0a0f65ff83f62/lib/openstudio-standards/prototypes/common/objects/Prototype.CentralAirSourceHeatPump.rb#L180) calculates and this [line](https://github.com/NREL/openstudio-standards/blob/b123fa6fc8e0e9b6307e63f4b1d0a0f65ff83f62/lib/openstudio-standards/prototypes/common/objects/Prototype.CentralAirSourceHeatPump.rb#L195) logs. They are linked by string matching. The `EnergyManagementSystem:CurveOrTableIndexVariable` is a pointer to the curve or table object. This object appears unnecessary (why just not reference the curve directly by name) but under the hood the curve/table calculations reference an index assigned to each curve. This object establishes that index. See [here](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/group-energy-management-system-ems.html#energymanagementsystemcurveortableindexvariable) for more information about the object itself, and [here](https://bigladdersoftware.com/epx/docs/9-5/ems-application-guide/built-in-functions.html#built-in-curve-and-table-functions) for details on how it can be used inside EMS programs (and why this object is necessary).

**Comment by MingboPeng** [comment]
Thanks @bonnema this is super helpful. Now I understand this curve object is being used by EMS program via  `EnergyManagementSystem:CurveOrTableIndexVariable`.  All clear now. I am closing this issue now. Thanks again.
