### ISSUE TITLE
model_add_typical_exterior_lights doesn't work for Laboratory building type

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#1151]
This is new building type in create_typical as well as create_prototype and create_bar measures. Everything in create_typical works except for this method. I tested with 90.1 2013 but issue may not be unique to that template.

`[16:57:19.346844 ERROR] :/ruby/2.7.0/gems/openstudio-workflow-2.2.0/lib/openstudio/workflow/util/measure.rb failed with message Runner error :/ruby/2.7.0/gems/openstudio-workflow-2.2.0/lib/openstudio/workflow/util/measure.rb failed with undefined method `>' for nil:NilClass, :/ruby/2.7.0/gems/openstudio-standards-0.2.13/lib/openstudio-standards/prototypes/common/objects/Prototype.Model.exterior_lights.rb:58:in `model_add_typical_exterior_lights'
:/ruby/2.7.0/gems/openstudio-extension-0.4.2/lib/openstudio/extension/core/os_lib_model_generation.rb:2894:in `typical_building_from_model'
/Users/dgoldwas/Documents/github/nrel/openstudio-model-articulation-gem/lib/measures/create_typical_doe_building_from_model/measure.rb:478:in `run'`

**Comment by DavidGoldwasser** [comment]
Work around for user for now was to turn set `add_exterior_lights` argument in measure to false and bypass this code, and add exterior lights through a separate measure or in seed model.

**Comment by mdahlhausen** [comment]
@DavidGoldwasser is this from testing the most recent create_typical gem? and what version of the openstudio-standards gem?  the error line Prototype.Model.exterior_lights.rb (line 58) doesn't match what I current have on the main branch.

**Comment by eringold** [comment]
I see this as: 
```
  Error: undefined method `>' for nil:NilClass
	:/ruby/2.7.0/gems/openstudio-standards-0.2.15/lib/openstudio-standards/prototypes/common/objects/Prototype.Model.exterior_lights.rb:62:in `model_add_typical_exterior_lights'
	:/ruby/2.7.0/gems/openstudio-extension-0.5.1/lib/openstudio/extension/core/os_lib_model_generation.rb:2992:in `typical_building_from_model'
```
which puts the offending line here: 
https://github.com/NREL/openstudio-standards/blob/67b0223d82fd32f8201969159f02a487dcf2f8e2/lib/openstudio-standards/prototypes/common/objects/Prototype.Model.exterior_lights.rb#L62

probably because one of these lookups is failing and returning an empty hash: 
https://github.com/NREL/openstudio-standards/blob/67b0223d82fd32f8201969159f02a487dcf2f8e2/lib/openstudio-standards/prototypes/common/objects/Prototype.Model.exterior_lights.rb#L341-L346
or 
https://github.com/NREL/openstudio-standards/blob/67b0223d82fd32f8201969159f02a487dcf2f8e2/lib/openstudio-standards/prototypes/common/objects/Prototype.Model.exterior_lights.rb#L366-L371

**Comment by DavidGoldwasser** [comment]
@mdahlhausen I think I posted this after last prior release. My guess is same issue as other new building types not having all data related to number or parking spots or other fields for exterior lighting.
