### ISSUE TITLE
Set U value of double glazing

### ISSUE THREAD

**Issue by agonzalezesteve** [NREL/openstudio-standards#1170]
I have problems with this double glazing window.

https://github.com/NREL/openstudio-standards/blob/e5276526c2424d8e4cd2011b6a7446a01e9ff3c5/lib/openstudio-standards/standards/ashrae_90_1/data/ashrae_90_1.constructions.json#L2557

The baseline measure tries to set the U value as a construction

https://github.com/NREL/openstudio-standards/blob/b460e90fe390d4336961ca77de8321b759956b51/lib/openstudio-standards/standards/Standards.Model.rb#L2410

but this method doesn't deal with fenestrations...

https://github.com/NREL/openstudio-standards/blob/b460e90fe390d4336961ca77de8321b759956b51/lib/openstudio-standards/standards/Standards.Construction.rb#L25

Then, the U value doesn't change to 3.12 W/m2 K.

**Comment by mdahlhausen** [comment]
Closing this.  

This kind of fenestration object can't be adjusted because the materials are explicit defined.  The fix is to replace the subsurface with a new simple glazing object with the baseline properties, which is what the PRM method now does.

The baseline measure is going to be replaced with PNNL's PRM baseline measure.  In the PRM baseline workflow in standards, the method replaces constructions with standard constructions instead of adjusting existing ones.
