### ISSUE TITLE
Geometry for Midrise Apartment is inside-out

### ISSUE THREAD

**Issue by asparke2** [NREL/openstudio-standards#119]
The geometry for the Midrise Apartment is inside-out:

This geometry was copied directly from the DOE Prototype Building IDF file, which is also inside-out:
![image](https://cloud.githubusercontent.com/assets/2009290/19701187/85d9845a-9ab7-11e6-8686-1ffbbdd89596.png)

The DOE Reference Buildings are correct:
![image](https://cloud.githubusercontent.com/assets/2009290/19701189/8909ccca-9ab7-11e6-9e15-c59ee7ac9652.png)

This did not show up in the comparison tests because both the OSM and the original IDF were wrong in the same way.

**Comment by eringold** [comment]
This is some Treehouse of Horror-type stuff. 
![tumblr_mcc04qq9vv1qzztl4](https://cloud.githubusercontent.com/assets/10799524/19702270/05f80464-9abc-11e6-8575-6d7cab435d0f.jpg)

**Comment by DavidGoldwasser** [comment]
@asparke2 I noticed that the first and second floors are not matched, but since the second floor has a multiplier of 2, seems like adiabatic is correct since the heat transfer would be asymmetrical. 

![screenshot 2016-11-02 10 11 52](https://cloud.githubusercontent.com/assets/4857055/19937230/f8c3ece2-a0e5-11e6-82aa-6fddf5efacbb.png)

If someone runs this model through surface matching for any reason it will automatically match the surfaces. Could be wise to raise the mid floor up so it is floating between the bottom and top floor, which is more typical configuration when zone multiplier is used as a 'floor multiplier'.

Although as devils advocate, idea of surface matching messing things up wouldn't be unique to this prototype building type, so maybe we should leave it alone? Another example is large hotel where multipliers are not just used as floor multipliers, but as a room multiplier. Could just have guideline 'Don't run surface matching on prototype geometry'. Hotel doesn't have an easy work around for this, unless surface matching is setup to ignore adiabatic surfaces.

**Comment by DavidGoldwasser** [comment]
For reference here is before and after end use breakdown. Total EUI was roughly 43.5 with old (reversed wall model) and 43.96 in fixed model. This run was done with hand fixed model. results when fixed geometry used in measure may be different if it affects sizing run or other characteristics. Heating end uses went down in the fixed model while cooling and fan consumption went up. Some zone conditions were affected as well.

![screenshot 2016-11-02 10 50 24](https://cloud.githubusercontent.com/assets/4857055/19938443/931308ec-a0ea-11e6-84a6-1ea10765fa0d.png)
