### ISSUE TITLE
SmallHotel prototype in almost every climate zones crashes

### ISSUE THREAD

**Issue by luisclv** [NREL/openstudio-standards#1328]
I am running all the PNNL commercial prototype buildings (16), in all 21 zones, across 6 standards(90.1-2004-2019) and I found that basically all the SmallHotel fail.

I am using OpenStudio 3.4.0. 

The EnergyPlus `err` file for ASHRAE 169-2013-0A, 90.1-2004 shows

```
   ** Severe  ** CalcHeatBalanceInsideSurf: The temperature of -19574.86 C for zone="ELEVATORCOREFLR1 ZN", for surface="W_ELEVATORCOREFLR1_3_0_0"
   **   ~~~   ** ..is very far out of bounds during warmup. This may be an indication of a malformed zone.
   **   ~~~   **  During Warmup & Sizing, Environment=HO CHI MINH TAN SON NHAT INTL ANN CLG .4% CONDNS DB=>MWB, at Simulation time=04/21 02:00 - 02:01
   **  Fatal  ** Program terminates due to preceding condition.
``` 

Steps to reproduce:

```ruby
require 'openstudio'
require 'openstudio-standards'
template = '90.1-2004'
building_type = 'SmallHotel'
climate_zone = 'ASHRAE 169-2013-0A'
epw_file = 'Not Applicable'
osm_directory = Dir.pwd
model = OpenStudio::Model::Model.new
prototype_creator = Standard.build("#{template}_#{building_type}")
prototype_creator.model_create_prototype_model(climate_zone, epw_file, osm_directory, false, model)
```

I pasted below the complete list of prototypes that failed (building type, climate zone, template)

```
SmallHotel,ASHRAE 169-2013-2A,90.1-2004
SmallHotel,ASHRAE 169-2013-1A,90.1-2004
SmallHotel,ASHRAE 169-2013-0B,90.1-2004
SmallHotel,ASHRAE 169-2013-3A,90.1-2004
SmallHotel,ASHRAE 169-2013-0A,90.1-2004
SmallHotel,ASHRAE 169-2013-1B,90.1-2004
SmallHotel,ASHRAE 169-2013-2B,90.1-2004
SmallHotel,ASHRAE 169-2013-0A,90.1-2007
SmallHotel,ASHRAE 169-2013-0B,90.1-2007
SmallHotel,ASHRAE 169-2013-1A,90.1-2007
SmallHotel,ASHRAE 169-2013-2A,90.1-2007
SmallHotel,ASHRAE 169-2013-3A,90.1-2007
SmallHotel,ASHRAE 169-2013-1B,90.1-2007
SmallHotel,ASHRAE 169-2013-2B,90.1-2007
SmallHotel,ASHRAE 169-2013-1A,90.1-2010
SmallHotel,ASHRAE 169-2013-0A,90.1-2010
SmallHotel,ASHRAE 169-2013-2A,90.1-2010
SmallHotel,ASHRAE 169-2013-3A,90.1-2010
SmallHotel,ASHRAE 169-2013-1B,90.1-2010
SmallHotel,ASHRAE 169-2013-0B,90.1-2010
SmallHotel,ASHRAE 169-2013-2B,90.1-2010
SmallHotel,ASHRAE 169-2013-2A,90.1-2013
SmallHotel,ASHRAE 169-2013-0A,90.1-2013
SmallHotel,ASHRAE 169-2013-1B,90.1-2013
SmallHotel,ASHRAE 169-2013-1A,90.1-2013
SmallHotel,ASHRAE 169-2013-0B,90.1-2013
SmallHotel,ASHRAE 169-2013-3A,90.1-2013
SmallHotel,ASHRAE 169-2013-2B,90.1-2013
SmallHotel,ASHRAE 169-2013-2A,90.1-2016
SmallHotel,ASHRAE 169-2013-0A,90.1-2016
SmallHotel,ASHRAE 169-2013-1B,90.1-2016
SmallHotel,ASHRAE 169-2013-1A,90.1-2016
SmallHotel,ASHRAE 169-2013-0B,90.1-2016
SmallHotel,ASHRAE 169-2013-3A,90.1-2016
SmallHotel,ASHRAE 169-2013-2B,90.1-2016
SmallHotel,ASHRAE 169-2013-0A,90.1-2019
SmallHotel,ASHRAE 169-2013-0B,90.1-2019
SmallHotel,ASHRAE 169-2013-2A,90.1-2019
SmallHotel,ASHRAE 169-2013-1B,90.1-2019
SmallHotel,ASHRAE 169-2013-1A,90.1-2019
SmallHotel,ASHRAE 169-2013-3A,90.1-2019
SmallHotel,ASHRAE 169-2013-2B,90.1-2019
SmallHotel,ASHRAE 169-2013-3B,90.1-2004
SmallHotel,ASHRAE 169-2013-3B,90.1-2007
SmallHotel,ASHRAE 169-2013-3B,90.1-2010
SmallHotel,ASHRAE 169-2013-3B,90.1-2013
SmallHotel,ASHRAE 169-2013-3B,90.1-2016
SmallHotel,ASHRAE 169-2013-3B,90.1-2019
SmallHotel,ASHRAE 169-2013-3C,90.1-2004
SmallHotel,ASHRAE 169-2013-3C,90.1-2007
SmallHotel,ASHRAE 169-2013-3C,90.1-2010
SmallHotel,ASHRAE 169-2013-3C,90.1-2013
SmallHotel,ASHRAE 169-2013-3C,90.1-2016
SmallHotel,ASHRAE 169-2013-3C,90.1-2019
SmallHotel,ASHRAE 169-2013-4C,90.1-2004
SmallHotel,ASHRAE 169-2013-4C,90.1-2007
SmallHotel,ASHRAE 169-2013-4A,90.1-2004
SmallHotel,ASHRAE 169-2013-4C,90.1-2010
SmallHotel,ASHRAE 169-2013-4A,90.1-2007
SmallHotel,ASHRAE 169-2013-4C,90.1-2013
SmallHotel,ASHRAE 169-2013-4A,90.1-2010
SmallHotel,ASHRAE 169-2013-4B,90.1-2004
SmallHotel,ASHRAE 169-2013-4C,90.1-2016
SmallHotel,ASHRAE 169-2013-4A,90.1-2013
SmallHotel,ASHRAE 169-2013-4B,90.1-2007
SmallHotel,ASHRAE 169-2013-4C,90.1-2019
SmallHotel,ASHRAE 169-2013-4A,90.1-2016
SmallHotel,ASHRAE 169-2013-4B,90.1-2010
SmallHotel,ASHRAE 169-2013-4A,90.1-2019
SmallHotel,ASHRAE 169-2013-4B,90.1-2013
SmallHotel,ASHRAE 169-2013-4B,90.1-2016
SmallHotel,ASHRAE 169-2013-4B,90.1-2019
SmallHotel,ASHRAE 169-2013-5A,90.1-2004
SmallHotel,ASHRAE 169-2013-5A,90.1-2007
SmallHotel,ASHRAE 169-2013-5B,90.1-2004
SmallHotel,ASHRAE 169-2013-5A,90.1-2010
SmallHotel,ASHRAE 169-2013-5B,90.1-2007
SmallHotel,ASHRAE 169-2013-5A,90.1-2013
SmallHotel,ASHRAE 169-2013-5B,90.1-2010
SmallHotel,ASHRAE 169-2013-5A,90.1-2016
SmallHotel,ASHRAE 169-2013-5B,90.1-2013
SmallHotel,ASHRAE 169-2013-5A,90.1-2019
SmallHotel,ASHRAE 169-2013-5B,90.1-2016
SmallHotel,ASHRAE 169-2013-5B,90.1-2019
```

**Comment by yunyangye** [comment]
I tested on my local for one case (SmallHotel, ASHRAE 169-2013-2A, 90.1-2004) by using two ways. The first one is through GUI (OpenStudio Application 1.4.0 and OpenStudio 3.4.0) and the second one is to use script (I used OpenStudio 3.4.0 and the newest version openstudio-standards ruby gem). Both ways worked and the model was generated without error. Which version of openstudio-standards did you use? I guess it may be caused by the version.

**Comment by luisclv** [comment]
I was working with 0.2.15, but then I updated the 0.2.16. I am attaching my output model for your case, could you share yours and we can run diffs?
[ashrae_169_2013_2_a.zip](https://github.com/NREL/openstudio-standards/files/8882345/ashrae_169_2013_2_a.zip)

**Comment by yunyangye** [comment]
Thanks for your file. I ran the idf sizing run on my Windows 10 machine without any issue. Did you run the file in Windows system or Linux system?

**Comment by luisclv** [comment]
I am running macOS 12.4

**Comment by yunyangye** [comment]
**First issue**: IDF file generated on my local machine is almost identical to the one you provided. There is only one input difference. The file should be identical regardless which system is used. 
**Second issue**: In addition, I also ran your idf file on my Windows machine and the simulation was completed without any error. This might be an issue for EnergyPlus.
We will investigate both first and second issues, and get the answer back to you.

**Comment by yunyangye** [comment]
@luisclv I also got the reply from EnergyPlus Support for the second issue. Do you think your mac computer is considered a qualified "Intel-based" Mac? I attached the reply from EnergyPlus Support here:

It is suggested to first check if there could be a hardware or os version comparability issue. One note about the Mac users is as follows (at [https://energyplus.net/installation#mac](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fenergyplus.net%2Finstallation%23mac&data=05%7C01%7Cyunyang.ye%40pnnl.gov%7C248236b44e914c6cd89f08da4e2c497b%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637908249354504818%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dcnwz4%2FQXNo1muvLmH988m%2FtQFHjQr3we9IjKFq3yUI%3D&reserved=0)):

"Notice for Apple Mac Users
At the present time, the Mac version of EnergyPlus is a subset of the Windows version and only runs on Intel-based Macs. The Mac version includes the EnergyPlus simulation engine and an interface to select input files and run a simulation. The Windows version of EnergyPlus includes additional utilities such as EP-Launch and IDF Editor which do not currently have Mac equivalents. IDF Editor is useful to simplify editing EnergyPlus input files. If you have a virtual Windows machine on your Mac (using VM Fusion or Parallels or similar), you may wish to also install the Windows version of EnergyPlus in order to access the additional utilities as needed."

**Comment by luisclv** [comment]
Hello everyone i am sorry for the late response. I am using arm64 (it is one of the new M1 Max MacBooks). Thank you for looking into it with the E+ team, I am pretty sure as of version 22 E+ has M1 native binaries, so the response is a little outdated. I agree with you, it looks like it is an issue with E+ and not openstudio-standards. Thank you for your help!
