### ISSUE TITLE
Investigate the Unmet Hours in Code

### ISSUE THREAD

**Issue by phylroy** [NREL/openstudio-standards#134]
Change the default tolerance for unmet hours to 1C for all models and determine effect from previous runs.

**Comment by phylroy** [comment]
https://github.com/NREL/OpenStudio-measures/tree/develop/NREL%20working%20measures/UnmetLoadHoursTroubleshooting

**Comment by phylroy** [comment]
Kamel to leave comments on fixes and assumptions.

**Comment by phylroy** [comment]
Waiting for Phylroy for fix #176

**Comment by khaddad** [comment]
Part of the problem for system 6 was due to the use of a damper action (reverse) that resulted in many underheated hours. This was changed to 'normal' action and this has reduced the # of underheated hours for offices and hotels. The offices the # of underheated hours is ~200-300 which is acceptable. This is mainly related to a core zone.

**Comment by phylroy** [comment]
Linked to SHW issue that Phylroy is working on for System 1. Pritorty to fix today. 
Kamel: To do a workaround for the sizing and post it to Unmet.
