### ISSUE TITLE
prm sizing run test causes git issues

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#1386]
[See this method](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.PlantLoop.rb#L98)
`def plant_loop_total_cooling_capacity(plant_loop, sizing_run_dir = Dir.pwd)`
The `Dir.pwd` causes the sizing run directory to be located wherever it is called from and can cause issues with commits.

**Comment by weilixu** [comment]
Hi @mdahlhausen, a quick question - are you running the test on Linus/WSL or Windows? Could you provide the file and script that runs into this problem? I can duplicate the issue and possibly fix it today.

**Comment by weilixu** [comment]
Some of the test case's directory length in the PRM test suit are longer than 260 char, which often result in error when trying to open those directories on Window (Window max char. directory is 260 characters). I wonder if this is because of this issue? 

There is a global variable at the top of `test_appendix_g_prm.rb`: `MAX_PATH_CHAR`. Could you se this variable to 200 and then run those failed test cases again and see if the error is resolved?

**Comment by mdahlhausen** [comment]
Update: this is a max path issue.  PNNL to fix by shortening test names.

**Comment by mdahlhausen** [comment]
Fixed with [this commit](https://github.com/NREL/openstudio-standards/commit/3a246b3a723222c40c069a33ed68ce82670186a6#diff-07bbb4609b65947068d7378d96135438fdb453aed96fc9500ae013171ffd4ddf).
