### ISSUE TITLE
Error across datapoints of different building types

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#144]
Hit this using prototype measure in 2x PAT project. Notice how error in retail model is about core and perimeter spaces from office model.

<img width="1912" alt="screen shot 2016-12-08 at 3 25 23 pm" src="https://cloud.githubusercontent.com/assets/4857055/21030366/62eca604-bd5b-11e6-9871-881c6d251acf.png">

**Comment by DavidGoldwasser** [comment]
@asparke2 possible this was also the cause of the error in issue #143 with baseline automation. 

Are you sure this only affects buildings of different building types. I'm thinking of use case where I have custom geometry in different design alternatives all running baseline automation.

**Comment by DavidGoldwasser** [comment]
Another error from that same run. This one small office

Error: undefined local variable or method `space_name' for #<OpenStudio::Model::Model:0x007fb2380401e0> /Users/dgoldwas/Applications/openstudio_1207b/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-standards-0.1.9/lib/openstudio-standards/prototypes/Prototype.Model.hvac.rb:387:in `get_return_plenum_from_system' /Users/dgoldwas/Applications/openstudio_1207b/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-standards-0.1.9/lib/openstudio-standards/prototypes/Prototype.Model.hvac.rb:19:in `block in add_hvac' /Users/dgoldwas/Applications/openstudio_1207b/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-standards-0.1.9/lib/openstudio-standards/prototypes/Prototype.Model.hvac.rb:16:in `each' /Users/dgoldwas/Applications/openstudio_1207b/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-standards-0.1.9/lib/openstudio-standards/prototypes/Prototype.Model.hvac.rb:16:in `add_hvac'

**Comment by asparke2** [comment]
@phylroy The root of this bug is similar to what was causing you to have problems with the tests.  Basically, the method load_building_type_methods was dumb.  What it does is dynamically load the correct building type's file.  Each of these files contains the same set of methods, but defined for a specific building type.  So what is happening is that when you run multiple runs in parallel, the methods are being redefined over and over again and can be in an unexpected state.  I'm going to move the building-type-specific methods into separate modules which I think will fix this.

**Comment by asparke2** [comment]
fixed by https://github.com/NREL/openstudio-standards/commit/55aa6b6082b8f4afb30b801927eec03ab85551a7
