### ISSUE TITLE
NECB service hot water loads + optionally add space names

### ISSUE THREAD

**Issue by boulterr** [NREL/openstudio-standards#148]
In creating the NECB models for Ottawa, I noticed that none of the models had any 'Water Use Equipment Definitions' assigned under Loads. All have water heating systems defined and sized where applicable. Kamel mentioned the loads may be built into the standards but I believe any water heating energy is more likely attributed to tank losses vs end use demand based upon the heating demand profiles. 

For example, looking at the E+ output summary for the Full Service Restaurant shows natural gas energy for Water Systems as 22.58 GJ (2.6% of site energy), but
Service Water Loop Pump water flow = 0.000000 m3/s; Electric Power = 0.000W; 
Water Heater 'Use Side Design Flow Rate' = 0.000000 m3/s
and average monthly SHW profiles (output variable: 'Water Heater Heating Demand') shows no demand - see attached profile summary.
[FullServiceRestaurant_NECB2011_Ottawa_ON.pdf](https://github.com/NREL/openstudio-standards/files/666933/FullServiceRestaurant_NECB2011_Ottawa_ON.pdf)

Models created from the nrcan branch of ...\openstudio-standards\openstudio-standards\test 'test_necb_bldg_<bldg_name>.rb' , OS v1.13.4

**Comment by jblake59** [comment]
**Update**
---
The problem is definitely due to missing water use equipment specified in the osm model. I'm digging into the problem in the add_swh() routine. The extracts below clearly require this input and Appendix A provides default values by building type and space but the unit for Service Water Heating load is "W/Person" and I was expecting L/Day/Person, or similar.

NECB 2011, 3rd printing. Section 8 Building Energy Performance Compliance Path
---
8.4.2.2. Calculation Methods paragraph 1) states that the energy model calculations shall
account for the annual energy consumption of ... e) **service water heating** equipment

8.4.2.7. Internal and Service Water Heating Loads
1) The energy model calculations shall account for the loads due to
a) number of occupants,
b) receptacle equipment,
c) **service water heating systems,** and
d) miscellaneous equipment, as applicable.

8.4.3.2. Operating Schedules
1) The operating schedules relating to the presence of occupants and of loads due
to the operation of lighting, receptacle equipment, and heating, cooling and **service
water heating** systems shall be representative of the proposed building's type or space
functions.

8.4.3.3. Internal and Service Water Heating Loads
1) Internal and **service water heating** loads used in the energy compliance
calculations shall be representative of the proposed building's type or space functions.

8.4.4.3. Internal and Service Water Heating Loads
1) The reference building's internal and **service water heating** loads shall be modeled
as being identical to those determined for the proposed building in Sentence 8.4.3.3.(1).

Appendix A-8.4.2.7.(1) ... Except for lighting, internal loads are not regulated within the scope of the NECB. However, because they add cooling and/or heating loads to the building’s HVAC and **service water heating systems**, internal loads representative of the building type or space function should be included in the compliance calculations in order to correctly evaluate part-load performance of the HVAC and service water heating systems and, by extension, the energy consumption of the proposed and reference buildings. The internal loads must be modeled identically in the proposed and reference building energy models; only the energy consumed by the equipment and systems regulated by the NECB can be modeled differently in the proposed and reference buildings.

**Comment by jblake59** [comment]
Problem in script (_below_) that checks for "Service Water Heating Peak Flow Rate (gal/h)" and "Service Water Heating Peak Flow per Area (gal/h*ft^2)". The logic aborts setting the flow rate when EITHER of these two values are zero or nil. The inputs in OpenStudio_Standards.xls, Space Types tab for the NECB 2011 template sets just one of these values, not both. The fix is to either modify the spreadsheet data or the code logic (i.e., change '||' to '&&' below). It's interesting that the NREL Template files have both set but ours (NECB 2011) only has the flow per unit area set (which makes more sense to me!).

Error in Prototype.hvac_systems.rb
def add_swh_end_uses_by_space(...)
  ...
      **if data['service_water_heating_peak_flow_per_area'].to_f == 0.0 ||
       data['service_water_heating_peak_flow_rate'].to_f == 0.0**
      return nil
...

**Comment by phylroy** [comment]
This is probably my fault...
There is a test here that if you run ensures that the space type data is correct, by doing a compare from previous output of the test.  https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/test/test_necb_default_spacetypes.rb
GitHub
NREL/openstudio-standards
Contribute to openstudio-standards development by creating an account on GitHub.
 



If you run the test it will create a file that will compare with this one here. https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/test/test_necb_default_spacetypes.rb

[3:22]  
You will notice that There are zeros  the the SHW columns... That should not be the case for most of them.

**Comment by jblake59** [comment]
This issue appears to be resolved.

Note: We are not assigning space names to the water use equipment. This is an optional step as described in the OpenStudio user documentation:

> Optionally you can associate the equipment with a space. There is no direct
energy use to the space, but heat from the equipment will be added to the space.

**Comment by phylroy** [comment]
Resolved
