### ISSUE TITLE
[Lighting]NECB Section 8.4.4.6(3) and 4.2.2.2 not being applied

### ISSUE THREAD

**Issue by phylroy** [NREL/openstudio-standards#164]
For some space types the LPD should be scaled by 0.9.  The potential solution is to create new space types that are applied if they meet the criteria by the user.. Ex. "Classroom/lecture/training LPD scaled 0.9"

Two ways come to mind:

1. Add new space types to the NECB list that have 0.9 factors included.
   a) Having a look at all the space types in question listed in 4.2.2(2a)
   b) Determine which space type needs to be duplicated with a LPD * 0.9
   c) Add this to the googledocs
   d) Modify the openstudio-standards/prototype/Prototype._buildingname_.rb 
       space_type_map for each building. 

2. Or have a rule that occurs after the space types have been assigned to change the LPD depending on the cirtieria in 4.2.2.

**Comment by jblake59** [comment]
For reference purposes, NECB 2011 states:

8.4.4.6(3): Where occupant sensors are required by Subsection 4.2.2., the installed interior
lighting power shall be multiplied by an adjustment **factor of 0.9**.

4.2.2.2(2): ...the control device shall be a) an occupant sensor that automatically extinguishes lighting in the following enclosed spaces within 30 minutes of their being unoccupied:
**i) classrooms and lecture halls, excluding shop and laboratory classrooms,
  ii) conference, meeting, and training rooms,
  iii) employee lunch and break rooms,
  iv) storage and supply rooms up to 100 m2,
  v) rooms used for document copying and printing,
  vi) office spaces up to 25 m2,
  vii) washrooms, and
  viii) dressing, locker, and fitting rooms**

**Comment by phylroy** [comment]
Hey Jeff. Here is a measure that adds 'occupancy control' by changing the LPD in select spaces.. you may be able to modify this for this task?
https://github.com/NREL/OpenStudio-PTool/blob/master/measures/occupancy_sensors_for_lighting/measure.rb

**Comment by jblake59** [comment]
Mapping 4.2.2.2(2) space type list to "Lighting Secondary Space Type" in "OpenStudio_Standards.xlsx:
i) --> Classroom/lecture/training
ii) --> Conf./meet./multi-purpose
iii) --> Lounge/recreation
iv) --> Storage area
v) --> ? (Office - enclosed)?, (Conf./meet./multi-purpose)?
vi) --> ? (Office - open plan)?, or (Office - enclosed)? Open plan has lower W/ft2.
vii) --> Washroom-sch-A (sch-A through sch-I have same W/ft2)
viii) --> (1) Dress./fitt. - performance arts, (2) Locker room, (3) Retail - dressing/fitting

**Comment by jblake59** [comment]
I've made the appropriate code change in Standards.SpaceType.rb using a check for the space type name containing one of the above strings and, if so, multiply the LPD (W/area) bu 0.9.  All of bundle exec rake test:gem_group_n passed except group_3 because the space_type_test_results.csv no longer matches space_type_expected_results.csv, as expected. Need to discuss what to do about this with @phylroy because I don't want to update the expected_results.csv file in Windows (CR/LF issue!).

**Comment by phylroy** [comment]
Mike to think about it and get back to Jeff Monday Feb 23, 2017.

We've thought about it and will make changes to the google doc and add spacetypes to reflect the 0.9 changes.

**Comment by jblake59** [comment]
Mike prefers that we don't include "Office - open plan" for application of the 0.9 LPD factor because of size of typical open plan office spaces. Occupancy sensors shouldn't be applied to the entire space.

After some further consideration, Jeff went back to application of the 0.9 LPD factor in code rather than creating new space type duplicates for list above. Was concerned that maintaining two rows of data for essentially the same space type would not happen consistently!

The test file test_necb_default_spacetypes.rb was modified to match the change in Standards.SpaceType.rb.

**Comment by jblake59** [comment]
I will look into this issue (#193)
