### ISSUE TITLE
Removal of HVAC in osm is causing  Segmentation fault in Prototype.utilities.rb

### ISSUE THREAD

**Issue by antonszilasi** [NREL/openstudio-standards#1709]
Upon attempting to call `standard.remove_hvac(model)` on a particular osm I receive a Segmentation fault in Prototype.utilities.rb.

I have encountered this bug in both OpenStudio-standards 0.4 and 0.5 and on Windows and Linux (Ubuntu)

I have attached the osm in question along with a small script to load it and call `standard.remove_hvac(model)` on it upon it to in a zipped directory here
[Remove HVAC system segmentation fault.zip](https://github.com/NREL/openstudio-standards/files/14580379/Remove.HVAC.system.segmentation.fault.zip)

![image](https://github.com/NREL/openstudio-standards/assets/8773483/f8363a2d-8e91-45ff-8043-92ef8fdc4f7c)

**Comment by mdahlhausen** [comment]
This is not an openstudio-standards issue. This is a segmentation fault in OpenStudio because of the duplicate types of zone equipment (2 ERVs and 2 PTHPs) in a single zone in the model. It's likely related to the way removing zone HVAC is handled [here](https://github.com/NREL/OpenStudio/blob/develop/src/model/ZoneHVACEquipmentList.cpp#L318-L363). You are welcome to resubmit this issue under OpenStudio.

Minimal steps to reproduce:
```
require 'openstudio'
osm_path = OpenStudio::Path.new('./PTHP with ERV.osm')
model = OpenStudio::Model::Model.load(osm_path).get

# simplify model to the one problematic zone and space
model.getAirLoopHVACs.each(&:remove)
model.getThermalZones.each { |z| z.remove unless z.name.get == 'ZE1-5' }
model.getSpaces.each { |s| s.remove unless s.name.get == 'aim1196' }

# trigger seg fault
model.getThermalZones.each do |zone|
  #next if zone.name.get.include?('ZE1-5')
  zone.equipment.each do |equipment|
    #next if equipment.name.get.include?('ERV')
    #next if equipment.name.get.include?('PTHP')
    puts "Attempting to remove #{equipment.name}"
    equipment.remove
  end
end
```
