### ISSUE TITLE
ERROR Could not find construction properties

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/openstudio-standards#179]
Running the current version of the Create Baseline Building measure from the BCL with Apply Measure Now in 1.14.0 produces the following error.

```
ERROR Could not find construction properties for: 90.1-20xx-ClimateZone 5-ExteriorDoor-RollUp-Nonresidential.
```

**Arguments**
* 90.1-2007 BETA, 90.1-2010 BETA, or 90.1-2013
* Warehouse
* 5B
* None

The model was created using the a block of code copied from the `Space Type and Construction Set Wizard` measure, which uses the [add_construction_set](https://github.com/NREL/openstudio-standards/blob/dad61d3483d1a0d404740357b371b645997f8b38/openstudio-standards/lib/openstudio-standards/standards/Standards.Model.rb#L2665) method.

Interestingly, running the measure on an identical model with `SolarCollectorFlatPlateWater` objects (and associated plant loop) added will produce the same error in 90.1-2007 BETA and 90.1-2013, but not 90.1-2010 BETA.

**Comment by mdahlhausen** [comment]
Summary of problem:
`lib\openstudio-standards\standards\Standards.Model.rb`
`model_create_prm_baseline_building()` -> 
`model_apply_standard_constructions() `-> 
`planar_surface_apply_standard_construction()` -> 
 This method gets the standards construction type from the construction, which is `RollUp`, rather than from the construction properties, which is `NonSwinging`.

Construction:
```
{
  "name": "Typical Overhead Door",
  "intended_surface_type": "ExteriorDoor",
  "standards_construction_type": "RollUp",
  "insulation_layer": "Typical Insulation",
  "skylight_framing": null,
  "materials": [
    "Typical Insulation"
  ]
}
```
Solution:
Add a check in the `planar_surface_apply_standard_construction()` method to change the standards construction type in the lookup for exterior door properties.
