### ISSUE TITLE
UA calculation failure in test_bldg_13

### ISSUE THREAD

**Issue by weilixu** [NREL/openstudio-standards#1829]
In PR #1823, `test_prm_baseline_bldg13` failed in the CI test.
Debugging reviewed that the failure is caused by `Surface 1624` and `Surface 1666`, 2 RoofCeilings in plenum space, have construction assigned as `Ffactor Ground Floor 4_005`, a `Construction:FfactorGroundFloor` object.

Due to the assignment of FfactorGroundFloor construction, the uFactor cannot be calculated and the test failed this specific [line](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/Standards.Surface.rb#L299).

Digging deeper in the test model file: [bldg_13.osm](https://github.com/NREL/openstudio-standards/blob/master/test/90_1_prm/models/bldg_13.osm), both `Surface 1624` and `Surface 1666` have no Construction assigned, and they both adjacent to a surface that has construction of `Ffactor Ground Floor 4_005`. It seems in this case, OpenStudio assigns the adjacent surface's construction as default for these two surfaces - and this causes the error in the failed line mentioned above.

I want to understand the intent of having a roof ceiling adjacent to a floor in this test case, since it was never a problem until now, especially the changes in PR #1823 has nothing to do with what we found here. - should I update the code to accommodate this behavior or modify the test file?

**Comment by mdahlhausen** [comment]
This seems like an issue in the base model and something we should catch in that method. Working on a fix. Thanks for making an issue!

**Comment by mdahlhausen** [comment]
Thoughts:
- I'm not able to recreate the error running the test on windows or linux with OS 3.7 or 3.8.
- This error appears in the surface_subsurface_ua() method. The surface_subsurface_ua() method is used only in space_conditioning_category(). surface_subsurface_ua() can probably be replaced, or refactored and moved to the Constructions module.
- As you described, the error is caused by a surface adopting the contruction of the adjacent surface, an FfactorGroundFloor construction, which does not have a U factor.
- The model is malformed - to surfaces are adjacent, but one is assigned an FfactorGroundFloor construction. That ought to not be a valid construction for surfaces with another surface as the boundary condition.

Fixes:
- Delete the FfactorGroundFloor construction assignment for the two adjacent surfaces; that construction was only used on those two surfaces. Have the adjacent surfaces use the default construction.
- Add a check to make sure the optional U factor is initialized.

**Comment by weilixu** [comment]
> Thoughts:
> 
> * I'm not able to recreate the error running the test on windows or linux with OS 3.7 or 3.8.
> * This error appears in the surface_subsurface_ua() method. The surface_subsurface_ua() method is used only in space_conditioning_category(). surface_subsurface_ua() can probably be replaced, or refactored and moved to the Constructions module.
> * As you described, the error is caused by a surface adopting the construction of the adjacent surface, an FfactorGroundFloor construction, which does not have a U factor.
> * The model is malformed - to surfaces are adjacent, but one is assigned an FfactorGroundFloor construction. That ought to not be a valid construction for surfaces with another surface as the boundary condition.
> 
> Fixes:
> 
> * Delete the FfactorGroundFloor construction assignment for the two adjacent surfaces; that construction was only used on those two surfaces. Have the adjacent surfaces use the default construction.
> * Add a check to make sure the optional U factor is initialized.

Thanks Matt. I also tried it on master branch and it worked fine. Somehow the AppxG branch triggers the error. Your PR resolved this issue by updating the base model. I did also updated the surface_subsurface_ua but I will merge your since it is part of the fix. Thank you for your attention and put on a fix in a short time period.
