### ISSUE TITLE
Boiler Min Unloading ratio

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#245]
Shouldn't we default the "MinimumPartLoadRatio" around [here](https://github.com/NREL/openstudio-standards/blob/a0794ce29bdcfaac23170e37f7b184d2186ff983/openstudio-standards/lib/openstudio-standards/prototypes/Prototype.hvac_systems.rb#L72)?

That would be following PNNL Table 69, so for a NaturalGas BoilerHotWater, should be 0.25.

![screen shot 2017-05-19 at 1 40 13 pm](https://cloud.githubusercontent.com/assets/5479063/26246305/b883d080-3c98-11e7-99b0-dcb4afbd5700.png)

**Comment by jmarrec** [comment]
This appears to be done for NCEB only, and here: https://github.com/NREL/openstudio-standards/blob/73d09fff27ac00da15d521bc817092159b6f3c0d/openstudio-standards/lib/openstudio-standards/standards/Standards.BoilerHotWater.rb#L135

**Comment by jmarrec** [comment]
Let me know if you want me to open a PR with the commit I just pushed or not (after we decide if its the right call and right place to put it)

**Comment by asparke2** [comment]
Agree this is needed, probably should add to [this method](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/Standards.BoilerHotWater.rb#L114).

**Comment by jiangithub** [comment]
In general, the prototypes are to follow the 90.1 App G modeling rules. However, in order to capture savings of boiler staging requirement, we have used an EMS to change the boiler curves for different boiler turndown ratios (see section 5.2.2.5 Addendum 90.1-2010am: Boiler Turndown in https://www.energycodes.gov/sites/default/files/documents/901-2013_finalCommercialDeterminationQuantitativeAnalysis_TSD_0.pdf) . This EMS method is not implemented in the current OpenStudio prototypes yet but we plan to do that. 
No matter what we do, I don't believe EnergyPlus can capture the cycling of boiler with a minimum ratio. Instead, the curves or Minimum Part Load Ratio are only to count the minimum gas energy use of the boiler. 
When we work on the PRM for 90.1-2019, we will have to revisit this about how to capture the App G rules.
