### ISSUE TITLE
add_doas with ERV doesn't increase pressure

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#271]
I'm reading this quickly (and haven't really tested the output), but it seems that when there is an ERV you meant to increase the fan pressure rise by 1 inH2O (set to 2.5 a few lines above), but I think you're just setting it to 1 inH2O:

https://github.com/NREL/openstudio-standards/blob/fde06f85f784d6e1fdf093ef955a9501d0adef22/openstudio-standards/lib/openstudio-standards/prototypes/Prototype.hvac_systems.rb#L4726

**Comment by asparke2** [comment]
I the increased fan power actually needs to be added via the power of the HX itself, because if the HX is being bypassed, the additional pressure rise would not be seen.  Pretty sure this is how the DOE prototype buildings handle it, but need to check.

**Comment by mdahlhausen** [comment]
The added fan power is captured through the electric power on the ERV, rather than to the fan.  This is because the added fan power should not apply when the ERV is bypassed.  This may be changed in the future if EnergyPlus and OpenStudio get smarter about handling static pressure calculations.

[Relevant section of code](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/prototypes/common/objects/Prototype.HeatExchangerAirToAirSensibleAndLatent.rb#L57-L64)

**Comment by jmarrec** [comment]
Permalink For future ref:

https://github.com/NREL/openstudio-standards/blob/5f85d7010a1a51823a3f8f570a1411a5888f5199/lib/openstudio-standards/prototypes/common/objects/Prototype.HeatExchangerAirToAirSensibleAndLatent.rb#L57-L64
