### ISSUE TITLE
Update locations elevation and heating degree days for NECB2015

### ISSUE THREAD

**Issue by khaddad** [NREL/openstudio-standards#276]
NECB 2015 Section: 8.4.2.3
Target Finish Date: 12-01-2017
Tester: Kamel
----------------------------------------------------------------------------------------------------------------

Table C-1 of the NECB 2015 has data for elevation and heating degree-days (18 C and 15 C). Currently this information is held inside BTAP in hash 'WeatherData1'. The data currently used in BTAP comes from the weather files. The hash 'WeatherData1' needs to be updated to use the data in Table C-1 of the NECB 2015. The hash doesn't have information on the heating degree-days for 15 C. A new field needs to be added to the hash to hold this information.

We have the data contained in Table C-1 in Excel format. A script needs to be generated to read this data and then to generate the hash 'WeatherData1'.

Any applicable unit tests need to be updated with the new weather data.

Run all the unit tests and make sure they pass.

Run all regression tests and make sure all changes can be attributed to changes made in this ticket.

**Comment by jblake59** [comment]
No problem. We already have a copy of this data in a spreadsheet in Git but don't use it yet in code. I have a feature issue input for using the spreadsheet directly [https://github.com/NREL/openstudio-standards/issues/163].

**Comment by jblake59** [comment]
The spreadsheet named "FutureUse_Weather-System_Data.xlsx" contains all of the information stored in the Ruby hash called "WeatherData1". The spreadsheet is in the btap folder in the openstudio-standards repository (i.e., openstudio-standards/openstudio-standards/lib/openstudio-standards/btap/). The spreadsheet need to be updated to contain the contents of Table C-1. Note that this spreadsheet is not yet used in code (see issue #163) but makes the maintenance of the "WeatherData1" has simpler. This has can be found starting in line 216 of Weather.Model.rb.

 Note though that we don't have new weather files (2016) for all the new locations in Table C-1. Also it seems that for some of the locations we currently support we have no new weather files for them. In this case we will keep using the older weather files.

**Comment by jblake59** [comment]
The weather files are maintained here: https://github.com/canmet-energy/weather-data

**Comment by khaddad** [comment]
We will for now focus on updating the data for the locations we currently support (~79 locations). If Table C-1 does not contain information for one of the locations, then we will keep using the same data we're currently using.  Other locations in Table C-1 will be dealt with when NRC sends us this Table in a better format.

**Comment by Shouldibuyacat** [comment]
Updated the spreadsheet created by Jeff to include a new column "hdd15", and updated the column "hdd18", and the elevation column to include the new data from Table C-1 of NECB 2015. (all changes highlighted in yellow)

Note: I did not change most of the major cities  yet because in Table C-1 they list them by either regions in the city or just by the city name itself, whereas in the spreadsheet and hash they are listed as being at the airport or in a location of the city that is different from the ones listed in table C-1.  Not sure what to do in cases like this.

Storing my changes here if you need to access them.

https://github.com/Shouldibuyacat/canmet-coop-resources/blob/master/FutureUse_Weather-System_Data_TysonUpdate.xlsx

Still working on connecting the spreadsheet with a script to create hash directly, and I will update the file as needed.
