### ISSUE TITLE
[Enhancement Request] Fix this ambiguous error message

### ISSUE THREAD

**Issue by HillJamison1** [NREL/openstudio-standards#322]
#I have a model that won't load in the OS App.  It produces an error message, "Original model contained XXXXX but final translated model is empty."  Replace this message with something more descriptive describing the error, what may cause it, and where the error occurred (line, col), to allow for for better debugging.

**Comment by mdahlhausen** [comment]
This is a warning message from [the OpenStudio version translator](https://github.com/NREL/OpenStudio/blob/3dac4fb844b89166cf7a651d9c14b91410ec0987/openstudiocore/src/osversion/VersionTranslator.cpp#L421-L425):
```
    LOG(Warn,"Expected final translated model to have " << numExpectedObjects
        << ", but it actually has " << m_nObjectsFinalIdf << " objects.");
    if ((m_nObjectsStart > 0) && (m_nObjectsFinalIdf == 0)) {
      LOG(Error,"Original model contained " << m_nObjectsStart
<< ", but final translated model is empty.");
```
The issue probably has to do with loading a newer model in an older version of OpenStudio or something related.  

Closing this issue here as it isn't openstudio-standards related.  Please repost with more information on the [OpenStudio issues page](https://github.com/NREL/OpenStudio/issues) if you want further resolution.
