### ISSUE TITLE
GetSiteFromBuildingComponentLibrary BCL measure fails with default parameters

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#449]
![all](https://user-images.githubusercontent.com/39242689/44753519-38a5a000-aad3-11e8-9aa0-d0931d55e587.PNG)

![default parameters](https://user-images.githubusercontent.com/39242689/44753478-11e76980-aad3-11e8-9d77-2defde8b4faf.PNG)

![failed](https://user-images.githubusercontent.com/39242689/44753484-157af080-aad3-11e8-8078-82ad21e13ef5.PNG)

**Comment by mdahlhausen** [comment]
This issue is not related to openstudio-standards.  It will be opened in openstudio-measures if it is still an issue.

@DavidGoldwasser this appears to be one of your BCL measures.  Can you recreate the issue?

**Comment by DavidGoldwasser** [comment]
It is on this repo now. Can file an issue there, and I an try to look at it, but the measure has other issues (see below)
https://github.com/NREL/openstudio-common-measures-gem/tree/develop/lib/measures/get_site_from_building_component_library

There was another issue either in PAT, OpenStudio, Server, or Workflow that affected using this in PAT, first datapoint worked, but following datapoints couldn't find the component. The issue for this was not something that can be fixed in the measure, so we have been using this measure instead, which is similar but requires you to pre-download weather files ahead of time
https://github.com/NREL/openstudio-common-measures-gem/tree/develop/lib/measures/ChangeBuildingLocation
