### ISSUE TITLE
PRM: reduce number of sizing runs

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#47]
At least some of the current sizing runs are not necessary. I'll look in more details tomorrow, but we can certainly get rid of at least the last one (just set each boiler sizing ratio to 0.5 if you have two of these...)

**Comment by asparke2** [comment]
@jmarrec here's my current thinking, let me know if you can see a way to avoid any of these.

SizingRunIdeal - To determine the heating/cooling loads on the zones for picking out exceptional zones.
SizingRun1 - Mainly to figure out the initial airflows to set fan power and perform multizone VAV damper minimum adjustment.
SizingRun2 - Only done if the VAV damper positions were adjusted.  Since this changes flow rates overall, I think this run is necessary before setting fan power.
SizingRun3 - Done after breaking single chillers and cooling towers into multiples.  Need the capacities of those objects to be able to set pumping types and apply minimum equipment efficiencies.  I think there is a possibility to get rid of this one by using the values from the previous sizing run and applying the new multipliers.  However, this would be tricky to get right I think.

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/commit/0eaf0d5fb82d57097bb8f0270fa7425af13318df

Was able to get rid of SizingRunIdeal because apparently the official interpretation is that the loads exception only applies to internal gains.  Was able to get rid of the SizingRun2 because changing the dampers positions didn't impact equipment sizing.  Could probably get rid of the last sizing run through some trickiness, but not going to do that right now.

**Comment by jmarrec** [comment]
That's great!
