### ISSUE TITLE
LargeOffice Model Floor Multiplier Still Missing

### ISSUE THREAD

**Issue by tsbyq** [NREL/openstudio-standards#561]
Looks like the issue was reported before (#175 ). However, the floor multipliers of the large office model created by "Create DOE Prototype Building" measure are missing. I also tried to create the model with openstudio-standards source code without the app. The results are the same.

The total floor area of the large office building should be 498,600 sqft (https://www.energycodes.gov/sites/default/files/documents/PNNL_Scorecard_Prototypes_Office_Large.xls). But the simulation results with the model created in OS is 153,412 sqft.

**Comment by sanghlee-lbnl** [comment]
Still LargeHotel, MidriseApartment, and Hospital model have the zone mulplier issue. 

- LargeHotel: guestroom zones (Total area should be 122,132 sqft, but OS is 62,769 sqft)
- MidriseApartment: apartment zones in middle floors (Total area should be 33,700 sqft, but OS is 25,296 sqft)
- Hospital: various zones for ER_exam, office, patroom (Total area should be 241,410, but OS is 214,017 sqft)

Note: HighriseApartment has the right number of apartment zones for mid floors instead of using multipliers. The modeling approach is different, but the total floor area is correct.

**Comment by mdahlhausen** [comment]
Fixed with #569
