### ISSUE TITLE
Enhancement request: method to apply "Schedule:Rule" for all days of week

### ISSUE THREAD

**Issue by amyeallen1** [NREL/openstudio-standards#568]
It would be useful to have a method to apply a Schedule:Rule for all days of the week, so that one wouldn't have to set the Rule to apply to each day of the week individually when all days of the week are desired.

**Comment by mdahlhausen** [comment]
Isn't that just a default schedule?

And where do you want this functionality?:
1) As a button in the OpenStudio app to apply the Schedule:Rule to all days of a week with one click instead of seven, or
2) Add a setApplyAllDays method to the [ScheduleRule object in the API](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.7.1-doc/model/html/classopenstudio_1_1model_1_1_schedule_rule.html)

**Comment by DavidGoldwasser** [comment]
@mdahlhausen both @amyeallen1 and I have had a need to make a rule that works on a specific calendar date for any year the schedule might be run. We have had to set the bool value for every day of the week to assure it works right. When you make a new ScheduleRule by default everything is set to false. This would just be a quick way to set them all to true. I don't think we need anything in the App, for this, just methods in API. Maybe setAllDays(bool), setWeekdays(bool), setWeekendsTrue(bool). We could add this in resource file loaded with measure or in standards, but seemed like it would be nice to add in modelAPI.

**Comment by mdahlhausen** [comment]
Moved to [OpenStudio issue #3441](https://github.com/NREL/OpenStudio/issues/3441).

**Comment by mdahlhausen** [comment]
@DavidGoldwasser @amyeallen1 this will be available in the next version of OpenStudio with https://github.com/NREL/OpenStudio/issues/3441
