### ISSUE TITLE
Add ASHRAE 90.1-2016

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#578]
A few inquires have come in on when we'll add 90.1-2016 to openstudio-standards.  We may want to do this after the refactor of the standards spreadsheet.

**Comment by asparke2** [comment]
One of the challenges with this is that 90.1-2016 Appendix G uses an entirely new methodology that basically reverts the baseline back to 90.1-2004 then calculates a % savings delta.  Long term, this will be nice because you won't have to re-implement baseline generation every year.  But for 90.1-2016, it means we'll need to implement both the 90.1-2016 code-minimum values and the 90.1-2016 Appendix G minimum values.  Probably need to make these 2 separate Standards in the code, since we'll want to be able to perform Appendix G baselines and simulation of typical buildings following 90.1-2016.

**Comment by mdahlhausen** [comment]
It seems there are two separate steps:
1) Add in 90.1-2016 data to the standards spreadsheet so that we can access those space, construction, and HVAC system properties through methods like the space type wizard and create typical building.
2) Add prototype model, Appendix Gbaseline model generation, and prm methods

Perhaps we can put in the code minimum values for now and save the App. G generation for next year?

**Comment by mdahlhausen** [comment]
This will be done as part of 2020 AOP work for openstudio-standards.

**Comment by MatthewSteen** [comment]
FYI Denver is in the process of adopting the 2018 IECC, which may affect Xcel Energy's EDA baseline requirements.

**Comment by MatthewSteen** [comment]
*There are no funded efforts to add 90.1-2016 to openstudio-standards this year.*

https://unmethours.com/question/42563/open-doe-901-2016-prototypes-in-openstudio/?answer=42580#post-id-42580

**Comment by mdahlhausen** [comment]
@MatthewSteen yeah, I thought it would be included under PNNL's 2020 AOP scope, but it seems it never got in there.  @jiangithub There are a lot of users requesting 90.1-2016.  I told them to encourage Amir to to fund the effort.  Any other thoughts on how users can advocate for this work to get funded?

**Comment by JasonGlazer** [comment]
You might want to consider suggesting to add support for the PRM for 90.1-2016 and 90.1-2019 at the same time. They are fairly similar.

**Comment by jiangithub** [comment]
@JasonGlazer HI Jason, PNNL has a task in this year to implement the PRM. We plan to do 90.1-2019 PRM directly. 
We don't have the resource to develop the OpenStudio DOE Commercial prototypes for the prescriptive requirements of 90.1-2016 or 2019 in this year.

**Comment by MatthewSteen** [comment]
The [90.1-**2004** argument](https://github.com/NREL/OpenStudio-measures/blob/develop/nrel_published/create_baseline_building/measure.rb#L27) in the Create Baseline Building measure is currently commented out but the measure "works" if it's not (i.e. generates a running baseline model). 

If the option to use `90.1-2004 BETA` in the measure is made available, that seems like it would allow users to at least get most of the way to a 90.1-2016 baseline.

**Comment by jiangithub** [comment]
> The [90.1-**2004** argument](https://github.com/NREL/OpenStudio-measures/blob/develop/nrel_published/create_baseline_building/measure.rb#L27) in the Create Baseline Building measure is currently commented out but the measure "works" if it's not (i.e. generates a running baseline model).
> 
> If the option to use `90.1-2004 BETA` in the measure is made available, that seems like it would allow for a quasi-automated 90.1-2016 baseline. Perhaps that's more of an NREL/OpenStudio-measures issue.

I cannot open the link but would like to point out the fundamental changes in Appendix G rules in Standard 90.1-2016 from its previous editions. Here are two papers that summarize the differences. 
http://www.eley.com/sites/default/files/pdfs/033-045_Rosenberg_WEB.pdf 
https://search.proquest.com/docview/1794511329?pq-origsite=gscholar 
I am not sure if `90.1-2004 BETA` is a reasonable approximation. If not, it may be OK to be used for research purposes but not good for actual design projects for code compliance and performance rating.

**Comment by asparke2** [comment]
The reason that 2004 was not enabled in this measure is because there were a few things that I knew were not implemented.  The biggest thing I can remember was the differences in glazing properties between directions.  But @MatthewSteen has a good point in that much of the code and data for the 2016 PRM can probably be copied from 2004 and the revised as necessary to save time.

**Comment by mdahlhausen** [comment]
Added in #1060.  Thanks to @lymereJ
