### ISSUE TITLE
PRM: Window-wall ratio calculation not consistent with EnergyPlus

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#64]
Testing PRM measure against an actual project. 

EnergyPlus reports:

| | Proposed | Baseline |
| --- | --- | --- |
| Gross WWR | 34.07% |  24.37% |
| Gross Conditioned WWR | 44.5% | 32.03% | 

PRM measure output shows (for the proposed model): 
"The WWRs are: NonRes: 57%, Res: 0%."

WWR code should return same results as EnergyPlus report (calculation [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/OutputReportTabular.cc#L9597)).

**Comment by asparke2** [comment]
@eringold Do I have this test model?  I'm thinking it could be one of two things:

1. This code does not yet take window frames into account (E+ does)
2. This code has a different determination of conditioned than E+.  The big difference is that E+ considers zones with just exhaust fans conditioned (like parking lots).

**Comment by jmarrec** [comment]
This is also related to whether you should include adiabatic surfaces in the "gross above ground exterior wall area" or not.

I've gone back and forth on this issue, initially I'd have not included it, now I think I would. We've also discussed whether we should really be treating anything as adiabatic in the case of a building abutting another. Additionally, I recognize that the general use case for adiabatic surface is to exclude them because it's usually when you're modeling only part of a building, or using zone multipliers.

Reading the code you linked @eringold it seems E+ is excluding it, it's also what eQuest is doing.

[UH: Wall boundary condition when abutting an adjacent building](https://unmethours.com/question/4709/wall-boundary-condition-when-abutting-an-adjacent-building/)

**Comment by asparke2** [comment]
According to the PNNL Performance Rating Method Reference Manual (yet to be published):

> **Nonresidential above grade exterior wall area** is defined as the gross above grade wall area for nonresidential conditioned space which only includes those walls that separate nonresidential conditioned spaces from the exterior.

Based on this definition, and assuming that adiabatic walls are used to represent either demising walls between your building and another conditioned building or are used in conjunction with zone multipliers to represent interior spaces, I do not think they should be included in the WWR calculation.

**Comment by eringold** [comment]
@asparke2 I'll email you the test model. I'm sure the discrepancy is the result of the different determination of conditioned spaces issue you mentioned. I admittedly wasn't aware that EnergyPlus took such a broad determination of 'conditioned', which does not seem to meet the ASHRAE definitions: 

![image](https://cloud.githubusercontent.com/assets/10799524/14960505/2fc6ed9a-1052-11e6-9671-0aba87d4ce6d.png)
![image](https://cloud.githubusercontent.com/assets/10799524/14960509/3aae83da-1052-11e6-9559-1b308c76e01c.png)

**Comment by asparke2** [comment]
@eringold FYI it was the plenums.  They were being considered unconditioned, and therefore not being included in the WWR calcs.

I wrote the code to do the full space conditioning category determination per ASHRAE as shown above, but in the interest of not doing another sizing run I'm currently using the heating and cooling setpoints for determination.  We'll see how this works out.

The annoying thing is that this could be an iterative process: WWR limits apply to each space conditioning category, which is determined by load.  And if you adjust the WWR, you impact the load...  Anyway, if it becomes necessary to use the full-bore official method, I think I'll run the load calcs on the unmodified proposed model and cache the space conditioning category for each space.  Then no matter how changing the constructions or WWRs changes the loads, the initially determined space conditioning category will apply.
