### ISSUE TITLE
PRM: Adds baseline system types that don't exist in early (non-addended) standards versions

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#67]
Baseline System Types 9 and 10 were not added to the major version of the ASHRAE 90.1 standard until 2010, yet the PRM measure is [adding them](https://github.com/NREL/openstudio-standards/blob/7d32e8ed3de795c6ebd9e2b2730fc4ec5a8fdaff/openstudio-standards/lib/openstudio-standards/standards/Standards.Model.rb#L506) when the standard version is 2004 or 2007.

**Comment by asparke2** [comment]
@eringold It's been a while since I've dealt with 2004 and 2007, but the way I read it now, the heated only spaces would use the regular nonresidential logic, in which case they get cooling systems as well.  Then, you are supposed to go and put those same cooling systems back into the proposed model for those zones.  Does this sound correct?

**Comment by jmarrec** [comment]
Baseline system types 9 and 10 were added as an addenda of 90.1-2007. Here's an extract of addendum dn and they were called 10 and 11:

![addendum dn](https://cloud.githubusercontent.com/assets/5479063/14950559/db883bc0-1052-11e6-9da1-f971bed00ae5.png)

A few programs that I use, such as the EnergyStar MFHR, force you to use the addendum...

Otherwise I agree with your interpretation Andrew, based on TABLE G3.1, section 10. HVAC Systems for the proposed building performance (emphasis is mine):

> The HVAC system type and all related performance parameters in the proposed design, such as equipment capacities and efficiencies, shall be determined as follows:

> a. Where a complete HVAC system exists, the model shall reflect the actual system type using actual component capacities and efficiencies.
b. Where an HVAC system has been designed, the HVAC model shall be consistent with design documents. Mechanical equipment efficiencies shall be adjusted from actual design conditions to the standard rating conditions specified in Section 6.4.1 if required by the simulation model.
c. Where no heating system exists or no heating system has been specified, the heating system classification shall be assumed to be electric, and the system characteristics shall be identical to the system modeled in the baseline building design.
**d. Where no cooling system exists or no cooling system has been specified, the cooling system shall be identical to the system modeled in the baseline building design.**
