### ISSUE TITLE
PRM Enthalpy Wheel Motor Power is High

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#729]
The method to calculate the Enthalpy Motor Wheel is [code here](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/prototypes/common/objects/Prototype.HeatExchangerAirToAirSensibleAndLatent.rb#L50-L53):
```
    # Calculate the motor power for the rotary wheel per:
    # Power (W) = (Minimum Outdoor Air Flow Rate (m^3/s) * 212.5 / 0.5) + (Minimum Outdoor Air Flow Rate (m^3/s) * 162.5 / 0.5) + 50
    power = (supply_air_flow_m3_per_s * 212.5 / 0.5) + (supply_air_flow_m3_per_s * 0.9 * 162.5 / 0.5) + 50
    OpenStudio.logFree(OpenStudio::Info, 'openstudio.prototype.HeatExchangerAirToAirSensibleAndLatent', "For #{heat_exchanger_air_to_air_sensible_and_latent.name}, ERV power is calculated to be #{power.round} W, based on a min OA flow of #{supply_air_flow_cfm.round} cfm.")
```

The equation yields values of ~1 kW for 3000 cfm and ~10 kW for 30000 cfm.  This is a lot of energy use, and well above the ~375 W and ~1500 W from [manufacturer specification sheets](https://www.novelaire.com/images/pdfs/ECWBrochure2008.pdf).

I'm wondering if there is an error in the code and dividing by 0.5 should instead be a multiply by 0.5.  Even then, the motor power is a bit high for large systems.

I can't find where the equation above came from.

@asparke2 thoughts?

**Comment by jiangithub** [comment]
@mdahlhausen PDF page 96 describes the assumptions of the formula. The power is not the energy for the ERV wheels but also the added fan power for additional pressure drop. 
https://www.pnnl.gov/main/publications/external/technical_reports/PNNL-20405.pdf

**Comment by asparke2** [comment]
@mdahlhausen yeah I remember coding this up and thinking the results were strange until I found out that the power includes the additional fan power for the pressure drop.  If I remember correctly, the reason that the fan pressure drop can't be modified directly is that when the ERV is bypassed, the fan pressure drop doesn't include the ERV, but in E+ the fan has a fixed pressure rise field.

An alternative to the current (and DOE prototype) method might be to use EMS to dynamically change the pressure rise on the fly using [this EMS actuator](https://bigladdersoftware.com/epx/docs/9-0/ems-application-guide/hvac-systems-001.html#fan).  This would correctly put the fan energy from the ERV into the "Fans" end use, but the EMS implementation could get cumbersome if there are lots of fans with ERVs inside the model.

Did you notice this because you saw a suspiciously high number in the "Heat Recovery" end use?  Getting the energy end use accounting right would be my main motivation to want to change methods.

**Comment by mdahlhausen** [comment]
@jiangithub and @asparke2 thank you for clarifying.  So we are capturing fan energy under the heat recovery end use to be able to capture the extra static pressure only when the wheel is active.

I ran into this in the ZE AEDG Multifamily project because we are showing high heat recovery energy use.  For now I'll communicate to the committee that most of this heat recovery energy is actually fan energy.

I do think we should find a way to include this under fan energy.  Ideally, that means an explicit static pressure calculation option in EnergyPlus.  This would be nice for the Autodesk plugin as well.  For now let's leave as is.
