### ISSUE TITLE
Support Ruby 2.5.1 for repo

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#746]
This isn't about using the standards gem on version of OpenStudio that uses Ruby 2.5.1 (3x) but using this repository as a developer with Ruby 2.5.1.

Hit this setting up new staff machines with Ruby 2.5.1

**Comment by asparke2** [comment]
To clarify, the request is to enable developers to use Ruby 2.5.1, which means that the `development dependencies` in `openstudio-standards.gemspec` must be compatible with Ruby 2.5.1.  Additionally, it means that in order to run tests, these developers will need a version of OpenStudio >= 3.0.0 ruby bindings, because the OpenStudio 2.X.X ruby bindings only work with Ruby 2.2.X.  These OpenStudio 3.0.0 and higher ruby bindings won't be available until ~April 2020.

**Comment by mdahlhausen** [comment]
Closed with #854
