### ISSUE TITLE
Deal with 90.1 minimum efficiency "As of XXXX"

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#75]
Example for Air Conditioners, 135-240 kBTU/h, electric resistance, in 90.1-2007 Table 6.8.1.A

> 9.7 EER (before 1/1/2010)
> 11.0 EER (After 1/1/2010)

In 2010 you also have a difference between before 2012 and after.

**Comment by asparke2** [comment]
Partially fixed by https://github.com/NREL/openstudio-standards/pull/106.   Need to go through and add date-specific efficiency ranges for 90.1-2004, 2007, and 2010.  2013 is done.  Depending on the types of equipment with date ranges in those other standards, make their Standards.Foo.rb files pass in the date ranges to the efficiency lookups.

**Comment by mdahlhausen** [comment]
Dates have long since been included in standards. Now formalized in the PNNL Building Energy Standards database.
