### ISSUE TITLE
Fan Power determination for small motors isn't following App G

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#76]
G3.1.2.9 Fan Motor Efficiency = the efficiency from Table 10.8 for the next motor size greater than the
bhp using the enclosed motor at 1800 rpm

To me this means that if bhp < 1 HP, you should look at 1 HP instead of "assuming PSC motor at 29% per a PNNL paper". I noticed that because the Section 1.4 tables from LEED were indicating my fan power for my "small" (<65 kBTU/h) PSZ-AC system group was way off.

I'll do a PR once I'm done working on my current project (for which I've modified a lot of code to suit my own needs)

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/pull/106.  Per 90.1-2010 addendum aj, as described in the [PNNL's Enhancements to ASHRAE
Standard 90.1 Prototype Building Models, 2.4.2 Fan Motor Efficiency](https://www.energycodes.gov/sites/default/files/documents/PrototypeModelEnhancements_2014_0.pdf),   most of these small motors fall in the 1/12 - 1 hp range and must therefore be EC motors or have an efficiency of 70%.  For standards before 90.1-2013, assume PSC motors at 29% efficiency.
