### ISSUE TITLE
Feature request: Expand MidriseApartment standards data

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#98]
It's missing Stairwells, Office, Community Room, Electrical/Mechanical, Exercise Room (Gym) etc. I don't think these should be classified as non residential.

**Comment by eringold** [comment]
uh, I think they should. Per ASHRAE 90.1 definitions:

**residential** = _spaces_ in buildings used primarily for living and sleeping. Residential spaces include, but are not limited to , dwelling units, hotel/motel guest rooms, dormitories, nursing homes, patient rooms in hospitals, lodging houses, fraternity/sorority houses, hostels, prisons, and fire stations.

**nonresidential** = all occupancies other than residential.

**Comment by KaiyuSun** [comment]
Do you mean these space types are missing in MidriseApartment prototype
models? But there are actually no stairs, community rooms or exercise rooms
in the DOE prototype/reference models for MidriseApartment.

**Comment by mirosenberg** [comment]
I agree with eringold. See this 90.1-2010 interpretation regarding non-residential spaces in residential buildings for some insight. https://www.ashrae.org/File%20Library/docLib/StdsInterpretations/IC-90.1-2010-26rev.pdf

**Comment by jmarrec** [comment]
Yeah nevermind. I was just looking at the output of the measure, the problem was actually that the dom_type and dom_fuel were incorrectly determined (array sorting needs reversing, and then heated only spaces do need to end up by themselves by G3.1.1 exception e

**Comment by amirroth** [comment]
There are no stairs in MidriseApartments? Isn't that a code violation? More seriously, several of the EnergyPlus prototype models are missing basic space types (I think the offices are missing most of them). It may be time to review which space types are in which model.

**Comment by KaiyuSun** [comment]
Yes...at least there isn't a zone 'named' as stair. We may bring this up at the coming workshop in PNNL.

**Comment by mirosenberg** [comment]
The offices are all just four and core simplified geometry. However, we do have an assumed space breakdown for calculation purposes such as space-by-space LPDs and occupancy sensor control. Other building types have more detailed geometry.

__________________________

Michael Rosenberg, CEM, LEED AP
Senior Research Scientist
ENERGY & ENVIRONMENT DIRECTORATE
Pacific Northwest National Laboratory
(509) 375-1995<tel:(509)%20375-1995>


On Jul 23, 2016, at 2:02 PM, amirroth <notifications@github.com<mailto:notifications@github.com>> wrote:


There are no stairs in MidriseApartments? Isn't that a code violation? More seriously, several of the EnergyPlus prototype models are missing basic space types (I think the offices are missing most of them). It may be time to review which space types are in which model.

**Comment by amirroth** [comment]
In general, we're going to want to go back and dress up these models with more realistic space plans and standard space types. The current approach works for EnergyPlus runs, but doesn't really work for OpenStudio measures, some of which are space-type sensitive. Offices are the first models to address, but we should opportunistically (or systematically) address all of them.

**Comment by jmarrec** [comment]
Is there a running list of things to address/bring up somewhere?

I'd like to add that LPD for Apartments be revised.

All programs for Multifamily buildings (LEED MFHR, NYSERDA MPP) that I've modeled for determine the LPD for apartment by looking up the Building Area LPD for "Multifamily". So 0.7 W/ft^2 for ASHRAE 90.1-2007 and 0.6 W/ft^2 for ASHRAE 90.1-2010 (TABLE 9.5.1). Currently openstudio-standards uses 0.36 + 0.09 W/ft^2 for pre-1980 and ASHRAE 90.1-2004, and 0.99 W/ft^2 for 189.1 (looking up Dormitory/Living Quarters). If you use ASHRAE 90.1-2007, 10 or 13 it ends up being 0.36 + 0.09 W/ft^2

**Comment by mirosenberg** [comment]
Amir,

I assume you are talking about the three office prototypes, as the others have detailed space inputs? I agree that the offices would benefit from this change. There are a couple of issues from our standpoint.


1.       As usual we are constrained by funding. We have a very long list of prototype enhancements that need to be made and we do those as we can afford them.

2.       The prototypes were developed specifically to support SSPC 90.1 and there is a working group that is made up from members of 90.1 and 189.1 that reviews and recommends changes. Typically things like which HVAC system type should be used in each prototype, but they would also want to weigh in on other major changes to any of the prototypes.

3.       As these models have been used to quantify savings for the 90.1 progress indicator, the DOE determination, and to develop code compliance targets we need to be careful to try and make changes in a way that do not have a big impact on those results. We lose credibility when savings goes from say 30% to 23% because of no change in the standard, but rather a change in our modeling assumptions.
Mike

**Comment by mirosenberg** [comment]
90.1 exempts lighting in dwelling units. Therefore prototypes use assumptions from the Building America program of 0.39 W/sqft for hard wired lighting and 0.09 W/sqft for plug in. Those assumptions are for all versions of 90.1.
